const STORAGE="car-ai-course-v1";
const state={route:"home",moduleId:null,data:loadState()};
function loadState(){try{return JSON.parse(localStorage.getItem(STORAGE))||{fields:{},done:{}};}catch{return{fields:{},done:{}};}}
function saveState(){localStorage.setItem(STORAGE,JSON.stringify(state.data));renderProgress();markNavDone();}
const modules=[
{id:1,day:"วันที่ 1 เช้า",title:"ปลดล็อกวิจัยชั้นเรียนและตั้งโจทย์",goal:"มีชื่อเรื่องวิจัยสั้น ชัด ใช้ได้จริง",output:"ปัญหา + สาเหตุ + ชื่อเรื่อง 1 ชื่อ",time:"2.5–3 ชม."},
{id:2,day:"วันที่ 1 สาย",title:"ถอดรหัสกระบวนการวิจัยในชั้นเรียน",goal:"วางแผนวงจร PAOR ของงานตนเองได้",output:"แผ่น PAOR 1 แผ่น",time:"1.5–2 ชม."},
{id:3,day:"วันที่ 1 บ่าย",title:"นวัตกรรมและเค้าโครงวิจัยด้วย AI",goal:"มีนวัตกรรมเล็กพอทำได้จริง และ CAR 1 หน้า",output:"แผนกิจกรรม 1 คาบ + CAR 1 หน้า",time:"3 ชม."},
{id:4,day:"วันที่ 2 เช้า",title:"เก็บข้อมูลและสถิติอย่างง่ายด้วย AI",goal:"สรุปผลเป็นภาษาคนได้โดยไม่ต้องจำสูตรยาก",output:"ตารางคะแนน + ย่อหน้าสรุป",time:"2.5–3 ชม."},
{id:5,day:"วันที่ 2 สาย",title:"ถอดบทเรียนและเขียน Best Practice",goal:"มีร่างที่ครูคนอื่นทำตามได้",output:"ร่าง Best Practice 5 หัวข้อ",time:"2.5 ชม."},
{id:6,day:"วันที่ 2 บ่ายท้าย",title:"เวทีแลกเปลี่ยนและประเมินผล",goal:"Pitch ได้ใน 3 นาที และมีแผน 30 วัน",output:"สคริปต์นำเสนอ + แผนหลังเรียน",time:"90 นาที"}
];
const prompts=[
{id:"p1",title:"ชุดที่ 1 สกัดปัญหาและคิดชื่อเรื่อง",text:"ฉันเป็นครูสอนวิชา [วิชา] ระดับชั้น [ชั้น] พบปัญหานักเรียน [พฤติกรรมที่สังเกตได้ + จำนวนคน] ช่วยวิเคราะห์สาเหตุที่ครูจัดการได้ในห้อง 3 ข้อ แล้วนวัตกรรม Active Learning ที่ทำได้ง่าย พร้อมชื่อเรื่องวิจัย 3 ชื่อ แบบ เป้าหมาย + นวัตกรรม + ตัวแปร + กลุ่มเป้าหมาย"},
{id:"p2",title:"ชุดที่ 2 ออกแบบแผนกิจกรรม",text:"ช่วยออกแบบแผนการเรียนรู้ 1 คาบ (50 นาที) เพื่อแก้ปัญหา [ปัญหา] โดยใช้นวัตกรรม [นวัตกรรม] ระบุ 1) วัตถุประสงค์ 2) ขั้นนำ ขั้นสอน ขั้นสรุปพร้อมเวลา 3) สื่อของที่มีในโรงเรียน 4) วิธีวัดผลสั้น ๆ"},
{id:"p3",title:"ชุดที่ 3 ประมวลผลคะแนน",text:"นี่คือคะแนนก่อน-หลังของนักเรียน [จำนวน] คน [วางตาราง] ช่วยคำนวณค่าเฉลี่ยก่อน-หลัง ร้อยละความก้าวหน้า=(หลัง-ก่อน)÷(เต็ม-ก่อน)×100 จำนวนคนผ่านเกณฑ์ [เกณฑ์] และเขียนย่อหน้าสรุปเชิงปรจักษ์ 6-8 บรรทัด ห้ามสร้างตัวเลขเพิ่ม"},
{id:"p4",title:"ชุดที่ 4 เขียน Best Practice",text:"ช่วยเขียนร่าง Best Practice เรื่อง [ชื่อเรื่อง] ผลคือ [ผลลัพธ์] ตามหัวข้อ 1) ความเป็นมา 2) วัตถุประสงค์ 3) ขั้นตอน PAOR 4) ผลลัพธ์ 5) บทเรียนที่ได้ ห้ามสร้างข้อมูลใหม่"},
{id:"g6",title:"ก6 ย่อ Pitch 3 นาที",text:"ย่องานของฉันให้พูดจบใน 3 นาที เปิดปัญหา / นวัตกรรม / ผล 1 ตัวเลขกับ 1 เหตุการณ์เด็ก / บทเรียนและแผนต่อ ข้อมูลคือ [วางข้อมูล]"}
];
function $(s){return document.querySelector(s)}
function el(h){const t=document.createElement("template");t.innerHTML=h.trim();return t.content}
function go(h){location.hash=h}
function parseRoute(){const p=(location.hash||"#/home").replace(/^#/,"").split("/").filter(Boolean);if(p[0]==="module")return{route:"module",moduleId:Number(p[1]||1)};if(["home","prompts","workbook","plan","about"].includes(p[0]))return{route:p[0],moduleId:null};return{route:"home",moduleId:null}}
function crumbText(r){return r.route==="home"?"หน้าหลัก / ภาพรวมหลักสูตร":r.route==="module"?`บทเรียน / โมดูล ${r.moduleId}`:r.route==="prompts"?"คลัง Prompt":r.route==="workbook"?"ใบงานของฉัน":r.route==="plan"?"แผน 30 วัน":"เกี่ยวกับคอร์ส"}
function doneCount(){return modules.filter(m=>state.data.done[m.id]).length}
function renderProgress(){const n=doneCount();$("#prog-label").textContent=n+" / 6 โมดูล";$("#prog-bar").style.width=Math.round(n/6*100)+"%"}
function markNavDone(){document.querySelectorAll(".nav-btn[data-id]").forEach(b=>b.classList.toggle("completed",!!state.data.done[b.dataset.id]))}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]))}
function field(id,label){return `<label class="field">${label}<textarea id="${id}">${escapeHtml(state.data.fields[id]||"")}</textarea></label>`}
function promptBox(p){return `<article class="prompt"><header><strong>${p.title}</strong><button class="btn sm gold" type="button" onclick="copyPrompt('${p.id}')">คัดลอก</button></header><pre id="txt-${p.id}">${escapeHtml(p.text)}</pre></article>`}
function moduleChrome(m){const prev=m.id>1?`<button class="btn ghost" onclick="go('#/module/${m.id-1}')">โมดูลก่อนหน้า</button>`:`<button class="btn ghost" onclick="go('#/home')">หน้าหลัก</button>`;const next=m.id<6?`<button class="btn teal" onclick="go('#/module/${m.id+1}')">โมดูลถัดไป</button>`:`<button class="btn teal" onclick="go('#/plan')">ไปแผน 30 วัน</button>`;return `<div class="check-row"><input type="checkbox" id="done-${m.id}" ${state.data.done[m.id]?"checked":""} onchange="toggleDone(${m.id}, this.checked)"><label for="done-${m.id}">ทำเครื่องหมายว่าเรียนจบโมดูลนี้แล้ว</label></div><div class="footer-nav">${prev}${next}</div>`}
function viewHome(){const cards=modules.map(m=>`<article class="mod-card" onclick="go('#/module/${m.id}')"><div class="tag">${m.day} · ${m.time}</div><h3>โมดูล ${m.id}  ${m.title}</h3><p>${m.output}</p></article>`).join("");return el(`<section class="hero"><div class="eyebrow">ONLINE COURSE · SPA</div><h2>วิจัยชั้นเรียนเปลี่ยนชีวิต<br>ปั้น Best Practice ติดปีกด้วย AI</h2><p>คอร์สปฏิบัติการ 6 โมดูล สำหรับครู</p><div class="meta"><span class="chip">2 วัน · 12 ชั่วโมง</span><span class="chip">เน้นปฏิบัติ 80%</span></div></section><h3 class="section-title">แผนที่การเดินทาง</h3><div class="grid cards">${cards}</div>`)}
function viewPrompts(){return el(`<section class="hero"><div class="eyebrow">PROMPT BANK</div><h2>คลังคำสั่งแม่บาบ AI</h2></section>${prompts.map(promptBox).join("")}`)}
function viewWorkbook(){const keys=Object.keys(state.data.fields).filter(k=>(state.data.fields[k]||"").trim());const list=keys.length?keys.map(k=>`<tr><td>${k}</td><td>${escapeHtml(state.data.fields[k]).slice(0,180)}</td></tr>`).join(""):`<tr><td colspan="2">ยังไม่มีข้อความที่บันทึก</td></tr>`;return el(`<section class="hero"><h2>ใบงานของฉัน</h2><div class="meta"><button class="btn ghost" onclick="exportWorkbook()">ดาวน์โหลด</button><button class="btn ghost" onclick="resetWorkbook()">ล้างข้อมูล</button></div></section><article class="lesson-card"><table><tr><th>รหัส</th><th>เนื้อหา</th></tr>${list}</table></article>`)}
function viewPlan(){return el(`<section class="hero"><h2>แผน 30 วัน</h2></section><article class="lesson-card"><table><tr><th>สัปดาห์</th><th>งาน</th></tr><tr><td>1</td><td>ปรับ CAR 1 หน้า และเตรียมสื่อ</td></tr><tr><td>2</td><td>เก็บ pretest และเริ่มสอน 3–6 คาบ</td></tr><tr><td>3</td><td>เก็บ posttest ใช้ Prompt ชุดที่ 3</td></tr><tr><td>4</td><td>เขียน Best Practice ฉบับสมบูรณ์</td></tr></table><div class="sheet">${field("plan_w1","สัปดาห์ที่ 1")}${field("plan_w2","สัปดาห์ที่ 2")}${field("plan_w3","สัปดาห์ที่ 3")}${field("plan_w4","สัปดาห์ที่ 4")}</div></article>`)}
function viewAbout(){return el(`<section class="hero"><h2>เกี่ยวกับคอร์สนี้</h2><p>ถอดโครงจากหลักสูตรวิจัยชั้นเรียนเปลี่ยนชีวิต ปั้น Best Practice ติดปีกด้วย AI</p></section><article class="lesson-card"><div class="kvs"><div>ต้นทางแนวคิด</div><div>นายอัมดิน กะสุเฒ่า โรงเรียนบ้านปูลาเจ๊ะมูดอ สพป.นราธิวาส เขต 2</div></div></article>`)}
const bodies={1(){return `<article class="lesson-card"><h3>โมดูล 1 จับปัญหาและตั้งชื่อเรื่อง</h3><div class="callout gold">วิจัยชั้นเรียนคือการสอนอย่างมีสติและบันทึกอย่างเป็นระบบ</div><p><strong>สูตรชื่อเรื่อง</strong> = เป้าหมาย + นวัตกรรม + ตัวแปร + กลุ่มเป้าหมาย</p><div class="sheet">${field("m1_beh","พฤติกรรมที่เห็นซ้ำ")}${field("m1_title_ai","ชื่อเรื่องที่เลือก")}</div>${promptBox(prompts[0])}</article>`},2(){return `<article class="lesson-card"><h3>วงจร PAOR</h3><div class="callout">คิดให้ชัด แล้วสอน แล้วดูของจริง แล้วเขียนสิ่งที่เรียนรู้</div><div class="sheet">${field("m2_p","P แผน")}${field("m2_a","A ลงมือ")}${field("m2_o","O หลักฐาน")}${field("m2_r","R สะท้อน")}</div></article>`},3(){return `<article class="lesson-card"><h3>นวัตกรรมและ CAR 1 หน้า</h3>${promptBox(prompts[1])}<div class="sheet">${field("m3_name","ชื่อนวัตกรรม")}${field("m3_car_title","ชื่อเรื่อง CAR")}${field("m3_car_prob","ปัญหาและความสำคัญ")}</div></article>`},4(){return `<article class="lesson-card"><h3>ข้อมูลและสถิติ</h3><div class="callout">ร้อยละความก้าวหน้า = (หลัง − ก่อน) ÷ (เต็ม − ก่อน) × 100</div>${promptBox(prompts[2])}<div class="sheet">${field("m4_pre","ค่าเฉลี่ยก่อน")}${field("m4_post","ค่าเฉลี่ยหลัง")}${field("m4_sum","ย่อหน้าสรุป")}</div></article>`},5(){return `<article class="lesson-card"><h3>Best Practice</h3>${promptBox(prompts[3])}<div class="sheet">${field("m5_bg","ความเป็นมา")}${field("m5_result","ผลลัพธ์")}${field("m5_lesson","บทเรียน")}</div></article>`},6(){return `<article class="lesson-card"><h3>Show & Share</h3>${promptBox(prompts[4])}<div class="sheet">${field("m6_open","ประโยคเปิด")}${field("m6_num","ตัวเลขที่อยากให้จำ")}${field("m6_next","แผน 30 วัน")}</div></article>`}};
function viewModule(id){const m=modules.find(x=>x.id===id)||modules[0];return el(`<section class="hero"><div class="eyebrow">${m.day} · ${m.time}</div><h2>โมดูล ${m.id}  ${m.title}</h2><p>${m.goal}</p></section>${bodies[id]()}${moduleChrome(m)}`)}
function render(){const r=parseRoute();state.route=r.route;state.moduleId=r.moduleId;document.querySelectorAll(".nav-btn").forEach(b=>b.classList.toggle("active",b.dataset.route===r.route&&String(b.dataset.id||"")===String(r.moduleId||"")));const root=$("#view");if(r.route==="home")root.replaceChildren(viewHome());else if(r.route==="module")root.replaceChildren(viewModule(r.moduleId));else if(r.route==="prompts")root.replaceChildren(viewPrompts());else if(r.route==="workbook")root.replaceChildren(viewWorkbook());else if(r.route==="plan")root.replaceChildren(viewPlan());else root.replaceChildren(viewAbout());$("#crumb").textContent=crumbText(r);closeSide();bindFields()}
function bindFields(){document.querySelectorAll("textarea").forEach(t=>t.addEventListener("input",()=>{state.data.fields[t.id]=t.value;saveState()}))}
function toggleDone(id,checked){state.data.done[id]=checked;saveState()}
function copyPrompt(id){const n=document.getElementById("txt-"+id);navigator.clipboard.writeText(n?n.textContent:"")}
function exportWorkbook(){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(state.data,null,2)],{type:"application/json"}));a.download="car-ai-workbook.json";a.click()}
function resetWorkbook(){if(!confirm("ล้างข้อมูล?"))return;state.data={fields:{},done:{}};saveState();render()}
function openSide(){$("#side").classList.add("open");$("#overlay").classList.add("show")}
function closeSide(){$("#side").classList.remove("open");$("#overlay").classList.remove("show")}
window.go=go;window.copyPrompt=copyPrompt;window.toggleDone=toggleDone;window.exportWorkbook=exportWorkbook;window.resetWorkbook=resetWorkbook;window.openSide=openSide;window.closeSide=closeSide;
window.addEventListener("hashchange",render);
window.addEventListener("DOMContentLoaded",()=>{renderProgress();markNavDone();if(!location.hash)location.hash="#/home";else render()});
